aws/jsii-compiler

- test/auto-accessors.test.ts
Auto accessor support was introduced in TypeScript 4.9 and allows introducing accessor-implemented properties (backed by an implicit `#private` property) using the `accessor` keyword. This is not compatible with the use of `readonly` (such properties are always read-write), and is useful to provide implementation of accessor-based abstract properties, or to override accessor-based parent members.
---
> chore: add test for auto-accessors

- test/property-inference.test.ts
Created tests to verify class property types can be inferred from their usage. Also tested to make sure that if the class property wasn't guaranteed to be defined, the compiler should output an error
---
> chore: Property Inference Tests

- src/assembler.ts
- test/string-literal-types.test.ts
Treat `{ [key: `template-${number}`]: T }` as equivalent to `{ [key: string]: T }` in the jsii type model, consistent with handling of `template-${number}` in other places.
Template string pattern index signatures was added in TypeScript 4.4.
---
> feat: accept template string pattern in index signatures

- src/assembler.ts
- src/jsii-diagnostic.ts
- test/__snapshots__/negatives.test.ts.snap
- test/negatives/neg.separate-write-type.ts
- test/string-literal-types.test.ts
Separate write types are allowed on property setters since TypeScript 4.3, where a setter can accept more types than the getter's return type, granted the getter's return type is assignable to the setter's argument. This is however not a feature that can be modeled in the jsii type system, or that can be accurately represented in several target languages (e.g: C#).
---
> feat: prohibit use of separate write type on properties

- fixtures/jsii-calc/lib/compliance.ts
- src/assembler.ts
ECMAScript `#private` identifiers are "truly" private (in contrast with how the TypeScript `private` keyword just hides declarations away from a type's declarations).
TypeScript does not support introducing these with the `private` keyword as it would be aking to a stutter. However, the `Assembler` needs to correctly detect private identifiers & treat them as private.
Also modified the `jsii-calc` suite to include several such members as a test that these are properly ignored.
---
> fix: #private members not ignored

- src/assembler.ts
- test/__snapshots__/negatives.test.ts.snap
- test/negatives/neg.index-signatures.ts
Index signatures cannot be represented in the jsii type model and should be rejected. TypeScript 4.3 also introduces support for static index signatures, which should be rejected, too.
Starting with TypeScript 4.4, Symbols can be used as keys on index signatures. Neither symbols nor index signatures are supported, but only the later should be reported (to avoid double-reporting issues).
---
> fix: correctly reject index signatures

- .github/workflows/release.yml
- .projen/tasks.json
- package.json
- projenrc/release.ts
- projenrc/tag-release.ts
Performs some checks before automatically picking the next version number according to options, and creates a new annotated git tag, optionally pushing it out to upstream.
---
> chore: add new tag-release command

- src/ambient/downlevel-dts.ts
- src/downlevel-dts.ts
If `downlevel-dts` has a different `semver` dependency instance than the jsii compiler, an `instanceof` check internal to `semver` fails and produces a `TypeError` exception. We can easily avoid this by always providing the target version as a `string`, which leads to `downlevel-dts` ultimately using its own `semver` instance to turn it into the `semver.SemVer` object it needs.
---
> fix: do not pass semver objects to downlevel-dts

- src/assembler.ts
- src/compiler.ts
- src/downlevel-dts.ts
- src/jsii-diagnostic.ts
- test/__snapshots__/negatives.test.ts.snap
- test/compiler.test.ts
- test/negatives/neg.index-signatures.ts
There may be internal use-cases for declaring indexer properties, and those can be erased using the `@internal` JSDoc tag. This allows using such declarations while explicitly hiding them from the library's API.
Additionally improved error messaging to remove related information when it points to types in the TypeScript standard library, as those are often fairly complex and their declaration is not expected to be shown to users.
---
> feat: allow marking indexers @internal

- src/assembler.ts
- src/directives.ts
- src/docs.ts
- src/jsii-diagnostic.ts
- test/__snapshots__/negatives.test.ts.snap
- test/directives.test.ts
- test/negatives/neg.index-signatures.ts
Users can annotate declarations with `@jsii ignore` to explicitly opt them out of cross-language support. This still allows the declaration to be visible to Javascript & TypeScript consumers of the library, but it is not included in the jsii assembly, and is hence not available for use in other languages.
Example usage:
```ts
export interface StructWithExtraProperties {
readonly propertyA: string;
readonly propertyB: number;
/**
* The index signature is not supported by jsii across languages. This
* allows it to be used in TypeScript and Javascript, but the library
* author should have an alternate (perhaps less convenient or less
* TypeScript-idiomatic) way to achieve the same intent for other
* languages.
*
* @jsii ignore
*/
readonly [key: string]: string | number;
}
```
This is …
> feat: add "@jsii ignore" directive

- src/downlevel-dts.ts
Failure to do so results in npm@>=6 using the `.gitignore` file instead, and hence causing all down-leveled declarations to be lost in the ether.
---
> chore: write .npmignore in .types-compat folder

- SUPPORT.md
Since we did not release 4.9.x.
---
> chore: support policy to mention 5.0.x instead of 4.9.x

- src/assembler.ts
- src/jsii-diagnostic.ts
- test/__snapshots__/negatives.test.ts.snap
- test/negatives/neg.generics.ts
The documentation says you can't use them, but the compiler never actually checked, and it silently ignored them (possibly reducing the type references to the "apparent type").
---
> feat: actually prohibit use of generic types

- fixtures/@scope/jsii-calc-base/lib/deep/index.ts
- fixtures/@scope/jsii-calc-base/lib/index.ts
- fixtures/@scope/jsii-calc-base/package.json
- fixtures/@scope/jsii-calc-lib/lib/index.ts
- fixtures/jsii-calc/package.json
- src/downlevel-dts.ts
- test/__snapshots__/integration.test.ts.snap
- test/integration.test.ts
The `typesVersions` directive applies recursively when the TypeScript compiler searches for the appropriate object to load... When attempting to resolve a directory, it will first rewrite that directory according to the typesVersions directive, and then it will rewrite the `index` sub-path within there again, resulting in two distinct rewrites happening within the same resolution. This appears to be a TypeScript bug as reported in microsoft/TypeScript#43133.
The work-around is to include a second rewrite candidate that explicitly targets the `*/index.d.ts` sub-path, which removes the need for a rewrite when searching down the `index` route.
Causes projen/projen#2570
--- …
> fix: deep-import of index files breaks ts3.9 compilers

- src/project-info.ts
Previously, `jsii` required the package's stability to be `deprecated` if there cas a `deprecated` message configured. This is however problematic when a `stable` package reaches End-of-Support and the maintainer wants to signal this in npmjs.com.
Instead of failing, only log a warning to possibly raise awareness on an unintended configuration.
Foward-ports: aws/jsii#4145
---
> feat: allow specifying a deprecation message regardless of stability

- .github/workflows/upgrade-maintenance-v5.0.yml
- projenrc/upgrade-dependencies.ts
Set `CI=false` in the upgrade workflow step that updates the `.projenrc` files so that `yarn projen` runs the `install` task and not the `install:ci` task (which does not allow locfile updates).
---
> chore: upgrade workflow fails on install:ci

- .github/workflows/auto-tag-dev-v5.0.yml
- .github/workflows/auto-tag-dev.yml
- .github/workflows/auto-tag-releases-v5.0.yml
- .github/workflows/auto-tag-releases.yml
- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/upgrade-main.yml
- .github/workflows/upgrade-maintenance-v5.0.yml
- .projen/deps.json
- .projenrc.ts
- package.json
- yarn.lock
The  upgrade-maintenance-v5.0 workflow is failing with the message:
```
error get-stream@7.0.0: The engine "node" is incompatible with this module. Expected version ">=16". Got "14.18.0"
```
---
> chore: update minNodeVersion to 16

- .github/workflows/release.yml
- projenrc/release.ts
Otherwise, the latest-dated release will be considered "the" latest, while we want this to only apply to the release that is tagged as "latest" on npm as well.
---
> chore: set latest flag on GitHub releases explicitly

- src/downlevel-dts.ts
The test that assesses whether down-leveled declarations are necessary or not accounted for the possible presence of duplicated references to `node` types being injected by the TypeScript compiler (microsoft/TypeScript#48143), however in some cases the reference is present more than twice, which was not correctly accounted for; resulting in emission of redundant down-level declarations.
---
> fix: unnecessary down-leveled declarations written

- projenrc/upgrade-dependencies.ts
> fix: update upgrade-dependencies to circumvent projen breaking changes

- .projen/tasks.json
- projenrc/upgrade-dependencies.ts
We do not use the `exclude` keyword and likely will not for the foreseeable future. Just dropping it for now. We will have to re-implement that if we need it but I don't see why we would -- this decision was also made in projen: https://github.com/projen/projen/pull/2845/files. This continues work started because projen had breaking changes.
---
> chore: fix upgrade-dependencies task

- package.json
- projenrc/upgrade-dependencies.ts
- yarn.lock
`upgrade-dependencies.ts` was recently [updated in Projen](https://github.com/projen/projen/pull/3014/files#diff-074cf384245372722fcc6b926e847b91b0b9652758d5a121e126470ec76051c5). This change needs to be synced with this repository for upgrade workflows to work correctly.
---
> chore: sync upgrade-dependencies.ts with projen

- src/tsconfig/validator.ts
- test/tsconfig/validator.test.ts
There was a proptest that failed in our test pipeline:
```
FAIL test/tsconfig/validator.test.ts
● Built-in matchers › Match.arrEq › pass
Property failed after 63 tests
{ seed: -1990728707, path: "62:2:64", endOnFailure: true }
Counterexample: [[[Number.NaN],[Number.NaN]]]
```
To fix this, I refactored the `looseEqual` helper. This also made some of the matcher code simpler.
Also added a few missing tests for some matchers.
In practice this is probably not very relevant, so I made this a chore.
---
> chore: fix failing tsconfig validator prop test

- .github/workflows/auto-tag-dev-v5.2.yml
- .github/workflows/auto-tag-dev-v5.3.yml
- .github/workflows/auto-tag-dev.yml
- .github/workflows/auto-tag-releases-v5.2.yml
- .github/workflows/auto-tag-releases-v5.3.yml
- .github/workflows/auto-tag-releases.yml
- .github/workflows/upgrade-maintenance-v5.2.yml
- .github/workflows/upgrade-maintenance-v5.3.yml
- .projenrc.ts
- projenrc/release.ts
- projenrc/tag-release.ts
- projenrc/upgrade-dependencies.ts
This repo was using an automatic backport feature for repository config. As part of daily upgrades, the projen config would be checked out from `main` and applied to maintenance branches. However because we also defined the current version in this config, this inadvertently changed the current version for maintenance branches as well! In practice that meant that the release tagging workflow tagged the wrong release lines.
This fix does two things: 
- Disable the automatic backport of configuration in favor of the new, explicit label based backport feature (see it in action on this PR!)
- Add an explicit release line option to the tagging workflow, that will be compared against the detected TypeScript version and fail if they don't match.
---
By submitting this pull request, I confirm that …
> chore: restore ability to release maintenance version lines

- src/docs.ts
When removing newlines in doc blocks, jsii it's leaving `\r` character on Windows. This appeared when doing https://github.com/projen/projen/pull/3582
The workaround is to replace the string in projects depending on jsii like projen. I did [a workaround here](https://github.com/projen/projen/pull/3582/commits/d6d8e54a2b4abcc9152d0b3c11eef4fcc73068bd).
Some examples of output from `console.log(util.inspect(myVar))` can be seen in this job, where the existing `\r` creates a newline when is not expected there and causes Node to throw `SyntaxError`s when using [`vm.runInContext`](https://github.com/projen/projen/blob/70b287e22b9913019a2a1113bc091e3cf2335bdb/src/projects.ts#L157)
https://github.com/projen/projen/actions/runs/9341376021/job/25708063745?pr=3582#step:6:467
```
'const …
```
> fix(docs): remove newlines on windows by replacing carriage return `\r\n` with spaces

- .github/workflows/auto-tag-dev-v5.2.yml
- .github/workflows/auto-tag-dev-v5.3.yml
- .github/workflows/auto-tag-dev.yml
- .github/workflows/auto-tag-releases-v5.2.yml
- .github/workflows/auto-tag-releases-v5.3.yml
- .github/workflows/auto-tag-releases.yml
- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/upgrade-main.yml
- .github/workflows/upgrade-maintenance-v5.2.yml
- .github/workflows/upgrade-maintenance-v5.3.yml
- .projenrc.ts
- projenrc/build-workflow.ts
- projenrc/common.ts
- projenrc/release.ts
upgrade workflows should use the latest lts version of node
build workflow should use the latest available version of the current major version for bug fixes
Backport from jsii-rosetta.
---
> chore: use latest node versions

- .github/workflows/build.yml
- projenrc/benchmark-test.ts
Adds check to not publish the benchmark metrics from a fork.
---
> chore: do not publish benchmark metrics from forks

- fixtures/@fixtures/jsii-composite/.gitignore
- fixtures/@fixtures/jsii-composite/.npmignore
- fixtures/@fixtures/jsii-composite/LICENSE
- fixtures/@fixtures/jsii-composite/NOTICE
- fixtures/@fixtures/jsii-composite/lib/index.ts
- fixtures/@fixtures/jsii-composite/package.json
- src/compiler.ts
- test/compiler.test.ts
Fixes #1070 
In the compiler constructor, the order of operations was not correct. This wasn't caught previously because we did not have a test case covering the automatic project references feature.
---
> fix: cannot resolve project references

- .github/workflows/build.yml
- projenrc/benchmark-test.ts
Workflow has been [broken](https://github.com/aws/jsii-compiler/actions/runs/9637586787/job/26577222425#step:5:90) as no value has been passed in to the metric dimension.
Tested it works [here](https://github.com/aws/jsii-compiler/actions/runs/9648974164/job/26611821291#step:5:8)
---
> chore: fix version line in JSII benchmark metric dimension

- src/docs.ts
Similar to https://github.com/aws/jsii-compiler/pull/1058, the Windows newline character wasn't matched and handled accordingly.
I found the problem in [this Github run](https://github.com/projen/projen/actions/runs/9536528729/job/26283592671?pr=3582#step:6:2043) which gives errors in snapshots, like the one below
```json
{
"default": "- No minimum version is being enforced",
-         "docs": "Minimal Major version to release.",
+         "docs": "Minimal Major version to release   This can be useful to set to 1, as breaking changes before the 1.x major release are not incrementing the major version number.  Can not be set together with `majorVersion`.",
"featured": false,
"fullType": {
"primitive": "number",
},
```
I tested that the changed works OK by packaging and installing jsii …
> fix(docs): split paragraphs by both Unix and Windows newlines

- .github/workflows/build.yml
- projenrc/benchmark-test.ts
> chore: fix typo in jsii slowdown metric version dimension

- .github/workflows/build.yml
- projenrc/build-workflow.ts
We had a PR https://github.com/aws/jsii-compiler/pull/1191 that got merged despite a failure in Node22 tests.
This happened because on a failure of one of the matrix builds, the job that is unifying them is skipped. This is documented behavior:
The fix is to make sure the combination step always runs and manually check the status of the matrix build.
---
> chore: fix ci PRs might get merged with failing tests

- src/tsconfig/rulesets/jsii-configured-options.ts
- test/tsconfig/tsconfig-validator.test.ts
When validating a tsconfig, the `outDir` config was incorrectly rejected with the following error message:
```
outDir: Unexpected field, got: outDir
```
This was due to a typo.
Relates to #1201 
---
> fix: outDir tsconfig is incorrectly rejected

- src/tsconfig/rulesets/incompatible-options.ts
- src/tsconfig/rulesets/strict.public.ts
- test/compiler.test.ts
- test/tsconfig/tsconfig-validator.test.ts
jsii will fail if no declarations are emitted.
This setting was not previously enforced, because tsc defaults to emitting declarations in some situations. However since its not the default for all allowed configurations, we should enforce it.
Also adds `emitDeclarationOnly: true` to the list of incompatible settings. Without compiled js files, jsii programs don't work either.
---
> fix(tsconfig): omitting `declaration` in custom config does not fail tsconfig validation

- src/assembler.ts
- src/compiler.ts
- src/downlevel-dts.ts
- src/helpers.ts
- test/downlevel.test.ts
Fixes #1234 
Also fixes an issue related the `.type-compat` output path that was discovered when adding tests. When getting `outdir` from the program, this might be either a relative or absolute path. Previously the code assumed it was always relative which is not correct. This led to absolute paths being used for the `.type-compat` dir and in the post processing; ultimately leading to a compilation failure. The fix is to ensure `outdir` & `.type-compat` are normalized to a relative path.
---
> fix: typesVersions not respecting outDir from tsconfig file

- src/tsconfig/rulesets/configurable-options.ts
- test/tsconfig/tsconfig-validator.test.ts
The `isolatedModules` & `isolatedDeclarations` options increase the strictness of the TypeScript compiler.
The `verbatimModuleSyntax` option is a modern replacement for a set of older options that influence if unused imports a
persevered in the JS output. As such it is irrelevant to the jsii type system and at the discretion of the user.
No testing required, as these are covered by the existing proptest.
---
> feat(tsconfig): mark verbatimModuleSyntax, isolatedModules & isolatedDeclarations options as configurable

- src/jsii-diagnostic.ts
- src/validator.ts
- test/__snapshots__/negatives.test.ts.snap
- test/negatives/neg.missing-abstract.ts
The following is a minimal reproducing example:
```ts
export interface ISomeInterface {
readonly xyz?: string;
}
export abstract class SomeClass implements ISomeInterface {
}
```
This breaks code generation for C#, as the `SomeClass._Proxy` class we generate will try to generate an `override` for the `Xyz` property, which is missing from the `SomeClass` class itself.
This issue is exhibited by a difference in logic between how we iterate the members of a class when we generate the class itself vs when we generate its proxy.
However, after looking at the code I'm not convinced it's correct either way (nor for Java), so to be safe we picked the solution where we force the user to declare the property on the class.
The correct declaration would be:
```ts
export abstract class SomeClass …
```
> fix: omitting optional property fails C# compilation

- src/tsconfig/compiler-options.ts
- test/compiler.test.ts
The `experimentalDecorators` flag is legacy from TypeScript 3.9.
Since then, decorators have gone through a large change and their new syntax, which is enabled by default in TypeScript 5+, looks very different.
Keeping this old flag enabled locks users into old decorator typings which are deprecated, plus because of the way our defaults are applied these flags are not overridable.
Instead, don't set `experimentalDecorators` at all, and have users opt in to legacy syntax if they must.
This is technically breaking, but I'm pretty sure this will affect such a negligible fraction of users that I think it's worth it.
---
[Apache 2.0 license]: …
> fix: disable experimental decorator flag

- src/support.ts
returns `"2025-04-03" ` instead of `"2025-04-03T22:04:47.424Z"`
---
> chore: report date and not time for end of support warning

- src/jsii-diagnostic.ts
Rephrase the error message of JSII9002, in order to addres #2082 a bit. We're not fixing the underlying issue, but we make it easier to find the workaround.
When using a purposely hidden interface as a shared base interface between multiple files, this only works if you add `@internal` to the documentation. The error message doesn't make that clear and in fact steers you away from the right solution and tells you to export the thing you didn't want exported.
Make the message bit more pithy and add the alternative out:
Old message:
```
Unable to resolve type "lib.Type". It may be @internal or not exported from the module's entry point (as configured in "package.json" as "main").
```
New message:
```
Type "lib.Type" is part of the public API but not exported (@internal or not exported from …
```
> fix: clarify remediations of JSII9002
